# ProxyCrypt Imaging
# ==================
#
# This workflow builds and registers images of ProxyCrypt.

---

name: ğŸ”‘ğŸŒÂ ProxyCrypt Imaging


# Triggers
# --------
#
# Run on any push to the docker or etc subdirs.

on:
    push:
        branches:
            -   main
        paths:
            -   'docker/**'
            -   'etc/**'


# Jobs
# ----
#
# What to do.

jobs:
    imaging:
        name: ğŸÂ Imaging
        runs-on: ubuntu-latest
        steps:
            -
                name: ğŸ’³Â Docker Hub Identification
                uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}
            -
                name: ğŸ“šÂ Repository Checkout
                uses: actions/checkout@v4
            -
                name: ğŸ°Â QEMU Multiple Machine Emulation
                uses: docker/setup-qemu-action@v3
            -
                name: ğŸš¢Â Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: ğŸ§±Â Image Construction and Publication
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: docker/Dockerfile
                    platforms: linux/amd64,linux/arm64/v8
                    push: true
                    tags: ${{secrets.DOCKERHUB_USERNAME}}/proxycrypt:latest

...

# -*- mode: YAML; tab-width: 4 -*-